version: 2.1
orbs:
  slack: circleci/slack@4.10.1

            
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [frontend-build]
      - run:
          name: Build front-end
          command: |          
            cd frontend
            npm install
            npm run build          
            
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          keys: [backend-build]
      - run:
          name: Back-end build
          command: |
             cd backend
             npm install
             npm run build
  
  test-frontend:
      docker:
        - image: circleci/node:13.8.0
        # Docker image here
      steps:
        # Checkout code from git
        - checkout
        - restore_cache:
            keys: [frontend-build]
        - run: 
            name: Run frontend test
            command: | 
              cd frontend
              npm install
              npm run test
        # Restore from cache
        # Your job code here
 
  test-backend:
      docker:
        - image: circleci/node:13.8.0
        # Docker image here
      steps:
        # Checkout code from git
        - checkout
        # Restore from cache
        - restore_cache:
            keys: [backend-build]
        # Your job code here
        - run:
            name: Run Backend test
            command: |
              cd backend
              npm install
              npm run test           

  scan-frontend:
    docker: 
      - image: circleci/node:13.8.0
      # Docker image here
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys: [frontend-build]
      # Your job code here
      - run: 
          name: Scan Frontend
          command: |
            cd frontend
            npm install
            # npm install oauth-sign@^0.9.0
            npm audit fix --audit-level=critical --force

  scan-backend:
    docker: 
      - image: circleci/node:13.8.0
      # Docker image here
    steps:
      # Checkout code from git
      - checkout
      # Restore from cache
      - restore_cache:
          keys: [backend-build]
      # Your job code here
      - run:
          name: Scan Backend
          command: |
            cd backe
            npm install
            # npm install oauth-sign@^0.9.0
            npm audit fix --audit-level=critical --force         
  
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          custom: |
            {
              "block":[
                {
                  "type": "section",
                  "fields": [
                      {
                        "type": "plain_text",
                        "text": "*This is a CircleCI notification*",
                        "emoji": true
                      }
                  ]
                }
              ]
            }
          event: always

workflows:
  default:

    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
  
  send-notification:
    jobs:
      - notify:
          context: slack-secrets
